# Generated by Django 4.2 on 2023-05-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("age", models.IntegerField()),
                ("admission_number", models.IntegerField(unique=True)),
                ("is_qualified", models.BooleanField(default=False)),
                ("average_score", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("student_capacity", models.IntegerField(default=0)),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True, related_name="classrooms", to="classroom.student"
                    ),
                ),
            ],
        ),
    ]
